### ISSUE TITLE
firefox mobile support feasible?

### ISSUE THREAD

**Issue by devinrhode2** [AlexisDrain/Less-Addictive-YouTube#1]
There's an alternative youtube app for youtube on Android, which notably gets rid of Shorts, but I'm too nervous about giving it my google login 

![Screenshot_20210701-084858](https://user-images.githubusercontent.com/539816/124135595-90b23d00-da49-11eb-88bc-6047d4bd1365.png)

**Comment by AlexisDrain** [comment]
I can't promise, but I'll look into it this week. :)

**Comment by poulrohan23** [comment]
thank you for this I have been using as my chrome add-on...works like a charm.

**Comment by AlexisDrain** [comment]
This is sadly hard to do considering I don't own an android phone. However, this plugin is opensource and I give anyone permission to port it to android (it might even work out of the box, but I cannot test it).

**Comment by AlexisDrain** [comment]
I enabled Firefox Android download on https://addons.mozilla.org/en-US/firefox/addon/less-addictive-youtube/ for version 1.36.

Like I said, I have not tested this version because I don't own an android phone. Please let me know if it works or not (I won't be able to fix it if it doesn't work).
