### ISSUE TITLE
librewolf

### ISSUE THREAD

**Issue by OrionRandD** [AlexisDrain/Less-Addictive-YouTube#2]
put librewolf and qutebrowser in your list please...

**Comment by OrionRandD** [comment]
> put librewolf and qutebrowser in your list please...

Works on librewolf    :)

**Comment by AlexisDrain** [comment]
I decided to only support Chrome and Firefox as this project is stressing me out. I won't be able to add those browsers, but feel free to fork this plugin and support them :)
