### ISSUE TITLE
Production/Store version broken on Firefox on Linux

### ISSUE THREAD

**Issue by jeettrivedi** [AlexisDrain/Less-Addictive-YouTube#4]
The extension broke sometime yesterday, I believe. None of the features appear to be working. Here is a screenshot of what I see. This is after refreshing the page after unchecking the options. I am on using Firefox 89.0.2 on Fedora KDE.
![image](https://user-images.githubusercontent.com/10325160/125317137-c5a27780-e306-11eb-85bc-437640ecdd45.png)

**Comment by AlexisDrain** [comment]
Thank you for notifying me! I reverted a change (starting content script on document_start vs document_idle) which should fix it. It will be published to the store within a day.

**Comment by jeettrivedi** [comment]
Wonderful, thank you!
